### ISSUE TITLE
MODIS years download

### ISSUE THREAD

**Issue by stineb** [computationales/ingestr#16]
When getting the "raw" data using `MODISTools::mt_subset`, we should get all available dates' data. Then, the the daily interpolated and gapfilled data can be reduced to years needed. Otherwise, we download raw data each time we use a different years specification.

This affects [this](https://github.com/computationales/ingestr/blob/07f851419a8cb5535658090c51c551a475b031fa/R/ingest_modis_bysite.R#L146) line.

**Comment by khufkens** [comment]
Keep in mind that data are non-static, but we're always at least a year behind on fluxes so not dramatic. This also relates to the priors issue as mentioned here.

https://github.com/computationales/ingestr/issues/28

**Comment by khufkens** [comment]
Fix by https://github.com/khufkens/ingestr/commit/f191f89e53f9f907511b4175614b3ecf8f81d132

will merge with next pull request
