### ISSUE TITLE
Land surface temperatures from MODIS Aqua AND Terra

### ISSUE THREAD

**Issue by stineb** [computationales/ingestr#32]
@khufkens 
For LST, the overpass time of the satellite is important. Now, ingestr downloads [MOD11A2](https://lpdaac.usgs.gov/products/mod11a2v006/). That is from the Terra satellite, which has an overpass time of 10.30 AM (see [here](https://modis.gsfc.nasa.gov/sci_team/pubs/abstract.php?id=07532#:~:text=Terra's%2010%3A30%20AM%20overpass,Aqua%20at%201%3A30%20AM.)). For planned applications (@martinabuck , @padasch ), where we use LST data to sense water stress, the later overpass time by the Aqua satellite at 1.30 PM is more directly relevant (will show larger difference between air and surface temperatures. Ideally, we get both. Data from Aqua and Terra (as their difference is also interpretable in the context of water stress). Aqua LST data is provided by the [MYD11A2](https://lpdaac.usgs.gov/products/myd11a2v006/) product, which is also available from ORNL DAAC and via MODISTools. Therefore, we should consider the following implementations (alternatives) in ingestr:

1. The bundle `"modis_lst"` downloads from both products (MOD11A2 and MYD11A2) and returns both variables after cleaning (no interpolation, see latest commit)
2. We make two bundles:  `"modis_lst_aqua"` and `"modis_lst_terra"`, returning one variable each after cleaning (no interpolation) and the user takes it from there.

In both cases, the overpass time should be added as a date-time object in the outputs (ok also to be added for other modis bundles, not just LST, but critical for LST). Critical: Is the overpass time zone the same as the one provided in the FLUXNET2015 data? 

I guess option 2 is to be preferred since it requires minimal changes to the code. Otherwise, taking two variables from two products forward might mess too much with the code structure as we have it now.

**Comment by khufkens** [comment]
Best to go with option 2 indeed to limit complexity.

It is best not to mix two steps (getting the data and processing the data).

Overpass times for MODIS if referenced should be constant (sun synchronous in time). However, for processed products this doesn't apply as you mix multiple dates.

**Comment by khufkens** [comment]
Integrated into GEE settings - no QC screening yet. But closed for now. https://github.com/computationales/ingestr/commit/790afc5eba51393d2d4c7308a655d0b0098bc173
