### ISSUE TITLE
CRAN compliance, declaring unstated variables

### ISSUE THREAD

**Issue by padasch** [computationales/ingestr#34]
@khufkens Could this be another copy-paste bug for the sections `# CRAN compliance, declaring unstated variables`

[Here](https://github.com/computationales/ingestr/blob/16fa75181c92322bfaa4cac7fc0c88c76602ee4b/R/ingest_bysite.R#L57) it messes up the function-call because input arguments are overwritten with NULL. The code works fine again when the following variables are removed from setting to NULL: `date_start` and `date_end`

That is, the code should be:
` 
problem <-
    year_start_tmp <- x <- y <- lat_orig <- success <- elv <- patm <-
    patm_base <-patm_mean <- month <- tavg <- temp <- temp_fine <-
    tmax <- tmax_fine <- tmin <- tmin_fine <- prec <- prec_fine <-
    days_in_month <- rain <- snow <- srad <- srad_fine <- ppfd <-
    ppfd_fine <- wind <- wind_fine <- qair <- vap <- vapr <- vapr_fine <-
    ilon <- data <- yy <- mm <- co2_avg <- year <- . <- bias <-
    co2 <- lon...1 <- lat...2 <- bottom <- top <- depth <- var <-
    var_wgt <- depth_tot_cm <- NULL
`

Probably there are other cases where this applies that I have not faced yet.

**Comment by khufkens** [comment]
Does a build check given you errors if you do?

**Comment by khufkens** [comment]
This now seems to run
