### ISSUE TITLE
Bug in code

### ISSUE THREAD

**Issue by stineb** [computationales/ingestr#44]
Commit e144dcd87e76dff34ee81130be3b26b3819c3be4 introduced a bug on [line 600 of `ingest_gee_bysite.R`](https://github.com/computationales/ingestr/blob/e144dcd87e76dff34ee81130be3b26b3819c3be4/R/ingest_gee_bysite.R#L600). 
`if else` sequence is wrong.

**Comment by khufkens** [comment]
https://github.com/computationales/ingestr/commit/db8922d26d2b1fd32bf7d738f055489935dfeeff

fixed per above, but the bit interpretation isn't transparent so most likely not correct

**Comment by khufkens** [comment]
returns a warning for this product
