### ISSUE TITLE
Error when ingesting "vpd" from CRU

### ISSUE THREAD

**Issue by lauramarques** [computationales/ingestr#50]
I got an error when trying to extract "vpd" from CRU via:

df_cru <- ingestr::ingest(
  siteinfo  = site,
  source    = "cru",
  getvars   = c("ccov","vpd"),
  dir       = "~/data/cru/ts_4.01/"
)

or

df_cru <- ingestr::ingest_bysite(
  sitename  = "CH-Lae",
  source    = "cru",
  getvars   = c("vpd"),
  dir       = "~/data/cru/ts_4.01/",
  timescale = "m",
  year_start = 1991,
  year_end  = 2019,
  lon       = 8.365,
  lat       = 47.4781,
  verbose   = FALSE
)

`Error in ingest_globalfields_cru_byvar(siteinfo, dir, "vap") : 
  Aborting. No files found for CRU variable vap`

It works good for ccov, tmax and tmin.

**Comment by stineb** [comment]
The error says you don't have the NetCDF files for vapour pressure locally (in your directory `~/data/cru/ts_4.01/`).
